### ISSUE TITLE
Error Running it with in docker it on Arm7 proccessor

### ISSUE THREAD

**Issue by scropion86** [mpherg/blynk-server#6]
Hello,

can you explain if you have build this image to run on a specific Architecture?
as i tried to run it on TV BOX which has Amlogic SOC 905X 
i got this error
`standard_init_linux.go:178: exec user process caused "exec format error"`
 as per [stackoverflow](http://stackoverflow.com/questions/42885538/raspberry-pi-docker-error-standard-init-linux-go178-exec-user-process-caused) because of different Architecture

**Comment by mpherg** [comment]
Sorry, this Docker image is built specifically for x86_64 architecture.
